'''
- Mapping of buildings to their info
- Functions that return a list of buildings with certain properties
'''

BLDG_INFO = {
    'AL099': ('99 Alexander (Forbes College)',),
    'ALEXH': ('Alexander Hall',),
    'ARCHB': ('Architecture Building',),
    'ARCHL': ('Architectural Laboratory',),
    'ARTMU': ('Art Museum',),
    'BENDC': ('Bendheim Center',),
    'BENDH': ('Bendheim Hall',),
    'BERLT': ('Berlind Theatre',),
    'BLAIR': ('Blair Hall',),
    'BOBSH': ('Bobst Hall',),
    'BOWEN': ('Bowen Hall',),
    'BR171': ('Broadmead, 171',),
    'BURRH': ('Aaron Burr Hall',),
    'C1879': ('Class of 1879 Hall',),
    'C1915': ('1915 Hall',),
    'CARRS': ('Career Services',),
    'CCAMP': ('Campus Club',),
    'CCAPA': ('Cap and Gown Club',),
    'CCHAR': ('Charter Club',),
    'CCLOI': ('Cloister Club',),
    'CCOLO': ('Colonial Club',),
    'CCOTT': ('Cottage Club',),
    'CENJL': ('Center for Jewish Life',),
    'CFCTR': ('Carl A. Fields Center',),
    'CHANC': ('Chancellor Green',),
    'CLIOH': ('Clio Hall',),
    'COMPU': ('Computer Science Building',),
    'CORWH': ('Corwin Hall',),
    'CQUAD': ('Quadrangle Club',),
    'CTERR': ('Terrace Club',),
    'CTOWE': ('Tower Club',),
    'DICKH': ('Dickinson Hall',),
    #('DILCE': ('Dillon Court East',),
    #('DILCW': ('Dillon Court West',),
    'DILLG': ('Dillon Gymnasium',),
    'ELPLE': ('Elementary Particles Lab East',),
    'ENOHA': ('Eno Hall',),
    'EPYNE': ('East Pyne Building',),
    'EQUAA': ('Engineering Quad - A Wing',),
    'EQUAB': ('Engineering Quad - B Wing',),
    'EQUAC': ('Engineering Quad - C Wing',),
    'EQUAD': ('Engineering Quad - D Wing',),
    'EQUAE': ('Engineering Quad - E Wing',),
    'EQUAF': ('Engineering Quad - F Wing',),
    'EQUAG': ('Engineering Quad - G Wing',),
    'EQUAJ': ('Engineering Quad - J Wing',),
    'FINEH': ('Fine Hall',),
    'FIRES': ('Firestone Library',),
    'FISHH': ('Fisher Hall',),
    'FITZO': ('FitzRandolph Observatory',),
    'FORBC': ('Forbes College Main',),
    'FORRT': ('Forrestal Campus',),
    'FRICK': ('Frick Chemistry Laboratory',),
    'FRIEN': ('Friend Center',),
    'FRIST': ('Frist Campus Center',),
    'GREEN': ('Green Hall',),
    'GUYOT': ('Guyot Hall',),
    'HAMIL': ('Hamilton Hall',),
    'HARGH': ('Whitman College Hargadon Hall',),
    'HENHO': ('Henry House',),
    'HOLDE': ('Holder Hall',),
    'HOYTL': ('Hoyt Chemical Laboratory',),
    'ICAHN': ('Carl Icahn Laboratory',),
    'IVY05': ('Ivy Lane, 5',),
    'JADWH': ('Jadwin Hall',),
    'JOLIN': ('Joline Hall',),
    'JONES': ('Jones Hall',),
    'LEWLI': ('Lewis Library',),
    'MADIH': ('Madison Hall',),
    'MARXH': ('Marx Hall',),
    'MCCKH': ('McCormick Hall',),
    'MCCOH': ('McCosh Hall',),
    'MCDON': ('James S. McDonnell Hall',),
    'MOFFH': ('Moffett Laboratory',),
    'MUDDL': ('Mudd Manuscript Laboratory',),
    'NA185': ('Nassau Street, 185',),
    'NA201': ('Nassau Street, 201',),
    'ORFES': ('Sherrerd Hall',),
    #('PAL01': ('Palmer Square',),
    'PEYTH': ('Peyton Hall',),
    'PRO58': ('58 Prospect',),
    'ROBEH': ('Robertson Hall',),
    'ROCKL': ('Rock Magnetism Laboratory',),
    'SCCAH': ('Scheide Caldwell House',),
    'SCHUL': ('Schultz Laboratory',),
    'STANH': ('Stanhope',),
    'STH91': ('Prospect Avenue, 91',),
    'THOML': ('Thomas Laboratory',),
    'VONNH': ('Von Neumann Hall',),
    'WALLB': ('Wallace Social Science',),
    'WHIGH': ('Whig Hall',),
    'WIL41': ('William Street, 41',),
    'WILCH': ('Wilcox Hall',),
    'WOOLC': ('Woolworth Music Center',),
    'WUHAL': ('Wu Hall',),
}

BLDG_CODE = tuple((code, info[0]) for code,info in BLDG_INFO.iteritems())


def getBldgsWithHours():
    pass

def getBldgsWithMenus():
    return ('WILCH', 'WUHAL', 'MADIH', 'FORBC', 'HARGH', 'CENJL', 'GRCOL')

def getBldgsWithLaundry():
    return ('WALKE', 'C1915', 'DICKH', 'BLAIR', 'BLOOM', 'BROWN', 'SCULL', 
            'YOSEL', 'BUYER', 'ENOHA', 'DODHA', 'EDWAR', 'FEINB', 'FORBC', 
            'HAMIL', 'HENRY', 'HOLDE', 'JOLIN', 'LITTL', 'LOCKH', 'CUYLE',
            'PYNEH', 'SCULL', 'SPELM', 'HARGH')

