'''
- Mapping of buildings to their info
- Functions that return a list of buildings with certain properties
'''

BLDG_INFO = {
    'AL099': ('99 Alexander (Forbes College)',),
    'ALEXH': ('Alexander Hall',),
    'ARCHB': ('Architecture Building',),
    'ARCHL': ('Architectural Laboratory',),
    'ARTMU': ('Art Museum',),
    'BENDC': ('Bendheim Center',),
    'BENDH': ('Bendheim Hall',),
    'BERLT': ('Berlind Theatre',),
    'BLAIR': ('Blair Hall',),
    'BOBSH': ('Bobst Hall',),
    'BOWEN': ('Bowen Hall',),
    'BR171': ('Broadmead, 171',),
    'BURRH': ('Aaron Burr Hall',),
    'C1879': ('Class of 1879 Hall',),
    'C1915': ('1915 Hall',),
    'CARRS': ('Career Services',),
    'CCAMP': ('Campus Club',),
    'CCAPA': ('Cap and Gown Club',),
    'CCHAR': ('Charter Club',),
    'CCLOI': ('Cloister Club',),
    'CCOLO': ('Colonial Club',),
    'CCOTT': ('Cottage Club',),
    'CENJL': ('Center for Jewish Life',),
    'CFCTR': ('Carl A. Fields Center',),
    'CHANC': ('Chancellor Green',),
    'CLIOH': ('Clio Hall',),
    'COMPU': ('Computer Science Building',),
    'CORWH': ('Corwin Hall',),
    'CQUAD': ('Quadrangle Club',),
    'CTERR': ('Terrace Club',),
    'CTOWE': ('Tower Club',),
    'DICKH': ('Dickinson Hall',),
    #'DILCE': ('Dillon Court East',),
    #'DILCW': ('Dillon Court West',),
    'DILLG': ('Dillon Gymnasium',),
    'ELPLE': ('Elementary Particles Lab East',),
    'ENOHA': ('Eno Hall',),
    'EPYNE': ('East Pyne Building',),
    'EQUAA': ('Engineering Quad - A Wing',),
    'EQUAB': ('Engineering Quad - B Wing',),
    'EQUAC': ('Engineering Quad - C Wing',),
    'EQUAD': ('Engineering Quad - D Wing',),
    'EQUAE': ('Engineering Quad - E Wing',),
    'EQUAF': ('Engineering Quad - F Wing',),
    'EQUAG': ('Engineering Quad - G Wing',),
    'EQUAJ': ('Engineering Quad - J Wing',),
    'FINEH': ('Fine Hall',),
    'FIRES': ('Firestone Library',),
    'FISHH': ('Fisher Hall',),
    'FITZO': ('FitzRandolph Observatory',),
    'FORBC': ('Forbes College Main',),
    'FORRT': ('Forrestal Campus',),
    'FRICK': ('Frick Chemistry Laboratory',),
    'FRIEN': ('Friend Center',),
    'FRIST': ('Frist Campus Center',),
    'GREEN': ('Green Hall',),
    'GUYOT': ('Guyot Hall',),
    'HAMIL': ('Hamilton Hall',),
    'HARGH': ('Whitman College Hargadon Hall',),
    'HENHO': ('Henry House',),
    'HOLDE': ('Holder Hall',),
    'HOYTL': ('Hoyt Chemical Laboratory',),
    'ICAHN': ('Carl Icahn Laboratory',),
    'IVY05': ('Ivy Lane, 5',),
    'JADWH': ('Jadwin Hall',),
    'JOLIN': ('Joline Hall',),
    'JONES': ('Jones Hall',),
    'LEWLI': ('Lewis Library',),
    'MADIH': ('Madison Hall',),
    'MARXH': ('Marx Hall',),
    'MCCKH': ('McCormick Hall',),
    'MCCOH': ('McCosh Hall',),
    'MCDON': ('James S. McDonnell Hall',),
    'MOFFH': ('Moffett Laboratory',),
    'MUDDL': ('Mudd Manuscript Laboratory',),
    'NA185': ('Nassau Street, 185',),
    'NA201': ('Nassau Street, 201',),
    'ORFES': ('Sherrerd Hall',),
    #'PAL01': ('Palmer Square',),
    'PEYTH': ('Peyton Hall',),
    'PRO58': ('58 Prospect',),
    'ROBEH': ('Robertson Hall',),
    'ROCKL': ('Rock Magnetism Laboratory',),
    'SCCAH': ('Scheide Caldwell House',),
    'SCHUL': ('Schultz Laboratory',),
    'STANH': ('Stanhope',),
    'STH91': ('Prospect Avenue, 91',),
    'THOML': ('Thomas Laboratory',),
    'VONNH': ('Von Neumann Hall',),
    'WALLB': ('Wallace Social Science',),
    'WHIGH': ('Whig Hall',),
    'WIL41': ('William Street, 41',),
    'WILCH': ('Wilcox Hall',),
    'WOOLC': ('Woolworth Music Center',),
    'WUHAL': ('Wu Hall',),
    
    '106AL': ('106 Alexander',),
    '114NA': ('U-Store/Labyrinth Books',),
    '11UNI': ('11 University Place',),
    '120PR': ('116/120 Prospect Apartments',),
    '126AL': ('120/126 Alexander',),
    '130AL': ('130 Alexander',),
    '136AL': ('132-134/136 Alexander',),
    '144AL': ('138-140/144 Alexander',),
    '169NA': ('169 Nassau',),
    '179NA': ('179 Nassau',),
    '180AL': ('172/180 Alexander',),
    '185NA': ('185 Nassau',),
    '1895F': ('1895 Field',),
    '1901H': ('1901 Hall',),
    '1938H': ('1938 Hall',),
    '1952S': ('1952 Stadium',),
    '1967H': ('1967 Hall',),
    '200EL': ('200 Elm',),
    '201NA': ('199/201 Nassau',),
    '221NA': ('221 Nassau',),
    '22CHA': ('22 Chamber St.',),
    '23UNI': ('23 University Place',),
    '29EDW': ('27/29 Edwards Place',),
    '31EDW': ('31 Edwards Place',),
    '35UNI': ('35 University Place',),
    '45UNI': ('41/45  University Place',),
    '48UNI': ('48 University Place',),
    '81ALE': ('81 Alexander',),
    'BAKER': ('Baker Rink',),
    'BEDFO': ('Bedford Field',),
    'BLOOM': ('Bloomberg Hall',),
    'BROWN': ('Brown Hall',),
    'BUYER': ('Buyers Hall',),
    'CALDW': ('Caldwell Fieldhouse',),
    'CAMPB': ('Campbell Hall',),
    'CHAPE': ('University Chapel',),
    'CLARK': ('Clarke Field',),
    'COGEN': ('Cogeneration Plant',),
    'CUYLE': ('Cuyler/Patton/Wright Hall',),
    'DENUN': ('DeNunzio Pool',),
    'DINKY': ('Dinky Station',),
    'DODHA': ('Dod Hall',),
    'EDWAR': ('Edwards Hall',),
    'FEINB': ('Feinberg/1937 Hall',),
    'FINNE': ('Finney/Campbell Field',),
    'FISHE': ('Fisher Hall',),
    'FOULK': ('Foulke Hall',),
    'FRELI': ('Frelinghuysen Field',),
    'GARDE': ('Garden Theater',),
    'GAUSS': ('Gauss/1939 Hall',),
    'GRADC': ('Graduate College',),
    'GULIC': ('Gulick Pavilion',),
    'HENRY': ('Henry Hall',),
    'JADWG': ('Jadwin Gym',),
    'LENZT': ('Lenz Tennis Center',),
    'LITTL': ('Little/Laughlin Hall',),
    'LOCKH': ('Lockhart Hall',),
    'LOWRI': ('Lowrie House',),
    'MACLE': ('Maclean House',),
    'MACMI': ('MacMillan Building',),
    'MCCAR': ('McCarter Theatre',),
    'MCCOS': ('McCosh Health Center',),
    'MURRA': ('Murray Dodge Hall',),
    'NASSH': ('Nassau Hall',),
    'NEWSO': ('New South Building',),
    'NTHGB': ('North Guard Booth',),
    'PALMH': ('Palmer House',),
    'POEFI': ('Poe/Pardee Field',),
    'POWER': ('Princeton Stadium/Powers Field',),
    'PYNEH': ('Pyne Hall',),
    'ROCKL': ('Rock Magnetism Laboratory',),
    'SCULL': ('1976/Wilf/Scully Hall',),
    'SEXTO': ('Sexton Field',),
    'SHEAR': ('Shea Rowing Center',),
    'SOUGB': ('South Guard Booth',),
    'SPELM': ('Spelman Halls',),
    'STRUB': ('Strubing Field',),
    'THEWA': ('The Wa',),
    'WALKE': ('1903/Walker Hall',),
    'WESTC': ('West College',),
    'WESTG': ('West Garage (Lot 7)',),
    'WITH': ('Witherspoon Hall',),
    'YOSEL': ('Yoseloff/Bogle Hall',),

    
}

BLDG_CODE = tuple((code, info[0]) for code,info in BLDG_INFO.iteritems())


def getBldgsWithHours():
    return set()

def getBldgsWithMenus():
    return set('WILCH', 'WUHAL', 'MADIH', 'FORBC', 'HARGH', 'CENJL', 'GRCOL')

def getBldgsWithLaundry():
    return set('WALKE', 'C1915', 'DICKH', 'BLAIR', 'BLOOM', 'BROWN', 'SCULL', 
            'YOSEL', 'BUYER', 'ENOHA', 'DODHA', 'EDWAR', 'FEINB', 'FORBC', 
            'HAMIL', 'HENRY', 'HOLDE', 'JOLIN', 'LITTL', 'LOCKH', 'CUYLE',
            'PYNEH', 'SCULL', 'SPELM', 'HARGH')

def getBldgsWithPrinters():
    return set()
